### ISSUE TITLE
why do you use Redis Pubsub 

### ISSUE THREAD

**Issue by HoangNgo88** [vortex314/redisDashboard#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by vortex314** [comment]
Hi , interesting question . I came to Redis via MQTT ( mosquitto ), I'm using Kafka in my professional context.
The reasons for redis :  
1. it's extemely fast as it is based on in-memory pub/sub compared to the others.  
2. in an IoT context you need small granularity of topics ands the ability to subscribe to a lot of them , in Kafka topics are heavy
3. the possibility in redis to use wild-card matching on topics
4. Redis is also a swiss army-knife, besides pub/sub it's also a key-value db, time series, streaming , search engine, JSON store,.. So in ths project I'm also using it to store dashboards
5.  It's a simple install and low in resource consumption. 
6. Other products based on MQTT assume that you have little data and random connections, in my approach to build robotics it's the contrary. So the latencies of MQTT are not acceptable in robotics
7. in my robotic concept the brain receives a lot of data and is close to the brain-stem (redis ) to have even lower latency . There is somewhere a plugin to have in-memory redis communication that goes even faster.
8. It runs perfectly and fast on a small raspberry pi ( the brain within a robot )

Hope this helps,
Lieven
